name: Deploy to EC2

on:
  push:
    branches: [ main ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install Server Dependencies
      run: |
        cd server
        npm install
        cd ..
        
    - name: Install Client Dependencies
      run: |
        cd client
        npm install
        cd ..
        
    - name: Build Client
      run: |
        cd client
        npm run build
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Navigate to project directory
          cd ~/shopify_SAAS
          
          # Pull latest changes
          git pull origin main
          
          # Deploy server
          echo "=== Deploying Server ==="
          cd ~/shopify_SAAS/server
          
          # Always run npm install for server (or check if package.json exists)
          if [ -f package.json ]; then
            echo "Installing server dependencies..."
            npm install --production
          else
            echo "No package.json found in server directory"
          fi
          
          # Restart server with PM2 (ecosystem.config.js is in root directory)
          cd ~
          pm2 restart ecosystem.config.js
          
          # Deploy client
          echo "=== Deploying Client ==="
          cd ~/shopify_SAAS/client
          
          # Check if client directory exists
          if [ -d "~/shopify_SAAS/client" ]; then
            # Install dependencies and build
            if [ -f package.json ]; then
              echo "Installing client dependencies..."
              npm install
              echo "Building client..."
              npm run build
              
              # Copy built files to nginx directory
              if [ -d "dist" ]; then
                echo "Copying built files to nginx..."
                sudo cp -rf dist/* /usr/share/nginx/html/shopify_client/
                sudo systemctl reload nginx
                echo "Client deployment completed successfully!"
              else
                echo "ERROR: dist directory not found after build"
                exit 1
              fi
            else
              echo "No package.json found in client directory"
            fi
          else
            echo "Client directory does not exist"
          fi
          
          # Final PM2 restart (ecosystem.config.js is in root directory)
          cd ~
          pm2 restart ecosystem.config.js
          
    - name: Notify on Success
      if: success()
      run: |
        echo "Deployment completed successfully!"
        
    - name: Notify on Failure
      if: failure()
      run: |
        echo "Deployment failed!"