name: Deploy to EC2

on:
  push:
    branches: [ main ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install Server Dependencies
      run: |
        cd server
        npm install
        cd ..
        
    - name: Install Client Dependencies
      run: |
        cd client
        npm install
        cd ..
        
    - name: Build Client
      run: |
        cd client
        npm run build
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "client/dist/*"
        target: "/tmp/client-build/"
        script: |
          # Navigate to project directory and pull latest changes
          cd ~/shopify_SAAS
          git pull origin main
          
          # Deploy server
          echo "=== Deploying Server ==="
          cd ~/shopify_SAAS/server
          
          if [ -f package.json ]; then
            echo "Installing server dependencies..."
            npm install --production
          else
            echo "No package.json found in server directory"
          fi
          
          # Deploy pre-built client files
          echo "=== Deploying Client ==="
          echo "Copying pre-built client files to nginx..."
          sudo rm -rf /usr/share/nginx/html/shopify_client/*
          sudo cp -rf /tmp/client-build/* /usr/share/nginx/html/shopify_client/
          sudo chown -R nginx:nginx /usr/share/nginx/html/shopify_client/
          
          # Restart services
          echo "=== Restarting Services ==="
          cd ~
          pm2 restart ecosystem.config.js
          sudo systemctl reload nginx
          
          # Cleanup
          rm -rf /tmp/client-build/
          
          echo "=== Deployment Complete ==="
          
    - name: Notify on Success
      if: success()
      run: |
        echo "Deployment completed successfully!"
        
    - name: Notify on Failure
      if: failure()
      run: |
        echo "Deployment failed!"