name: Deploy to EC2

on:
  push:
    branches: [ main ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install Server Dependencies
      run: |
        cd server
        npm install
        cd ..
        
    - name: Install Client Dependencies
      run: |
        cd client
        npm install
        cd ..
        
    - name: Build Client
      run: |
        cd client
        npm run build
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/shopify_SAAS
          git pull origin main
          
          # Deploy server
          cd server
          if git diff --name-only HEAD@{1} HEAD | grep -E 'package(-lock)?\.json'; then
            echo "package.json or package-lock.json changed, running npm install..."
            npm install
          else
            echo "No change in package.json or package-lock.json, skipping npm install."
          fi
          cd 
          pm2 restart ecosystem.config.js
          
          # Deploy client
          cd client
          if git diff --name-only HEAD@{1} HEAD | grep -E 'package(-lock)?\.json'; then
            echo "package.json or package-lock.json changed, running npm install..."
            npm install
          else
            echo "No change in package.json or package-lock.json, skipping npm install."
          fi
          npm run build
          sudo cp -rf dist/* /usr/share/nginx/html/shopify_client/
          sudo systemctl reload nginx
          sudo systemctl restart nginx
          cd 
          pm2 restart ecosystem.config.js
          
    - name: Notify on Success
      if: success()
      run: |
        echo "Deployment completed successfully!"
        
    - name: Notify on Failure
      if: failure()
      run: |
        echo "Deployment failed!"

    - name: Upload npm log
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: npm-log
        path: /home/runner/.npm/_logs/ 